---
title: 抓马的博客
timezone: Asia/Shanghai
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: 抓马的博客,抓馬,抓馬的博客,zhua.ma,熊の猫,熊的猫,一个博客树洞。本博客基于Jekyll进行书写。源自生活的点点滴滴和碎碎念。
baseurl: 'https://zhua.ma'
url: https://zhua.ma
author:
  name: 熊的猫
  url: https://zhua.ma/about/
  email: zhuama@163.net
markdown: kramdown
include:
- _pages
sass:
  sass_dir: _sass
  style: compressed
plugins:
- jekyll-feed
- jekyll-paginate
- jekyll-seo-tag
- jekyll-sitemap
permalink: "/post/:year:month:day.html"
paginate: 5
exclude:
- Gemfile
- Gemfile.lock
- muji.gemspec
